server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:bookstore
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bookstore
#    username:
#    password:
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true

springdoc:
  api-docs:
    enabled: true
app:
  jwtSecret: SecretKey1234
  jwtExpirationMs: 86400000